### ISSUE TITLE
esplora next release checklist

### ISSUE THREAD

**Issue by greenaddress** [Blockstream/esplora#43]
- [ ]  Separate mempool and fee estimation with a horizontal spacer

- [x] Add mempool to home page after Broadcast tx

- [x] Have 502 bad gateway similarly rendered as 404 and with a message like "Esplora is currently not available, perhaps it is still loading, please retry again later." - or maybe we could even have some kind of IDB/indexing progress?

- [x] Recent transactions remains populated even mempool is empty, which may be ok but depth wouldn't be applicable anymore?

- [x] Seeing things like "0.00 vMB from tip" is not nice, should we move to vKB or switch to "< 0.01 vMB from tip" ?

- [ ] When we suggest about overpaying - should we link to the estimation being used? Same about calculation for segwit/bech32

- [x] Refresh latest transifex languages update (Italian, etc)

**Comment by shesek** [comment]
- [ ] Move recent transactions to homepage

**Comment by shesek** [comment]
> Seeing things like "0.00 vMB from tip" is not nice, should we move to vKB or switch to "< 0.01 vMB from tip" ?

This should only show "0.00 vMB" if this is actually exactly 0, it won't be rounded down.

**Comment by shesek** [comment]
>  When we suggest about overpaying - should we link to the estimation being used? Same about calculation for segwit/bech32

Added an indication the recommended fee is coming from bitcoin'd estimations to the hover text. Should it also link to somewhere?

What could the segwit savings be linked to?

>  Separate mempool and fee estimation with a horizontal spacer

I've been playing with this, what I tried didn't look very good. Any specific ideas on how that should look?

**Comment by greenaddress** [comment]
> Figure out hover texts (they're generally considered a bad idea, and are especially unusable on mobile)

Maybe instead of hover just use an (i) icon for info which when clicked either redirects you to the info or shows you the info. Not sure how would that work with nojs.

**Comment by shesek** [comment]
>  Figure out how to split fee buckets for display

Ended up defining the fee buckets as fixed fee-rate ranges in steps of 50%. So 1-1.5, 1.5-2.25, 2.25-3.37, etc. This is similar to how bitcoin core defines its fee buckets, only that they're using 10% steps.

Note that this only effects the way fee buckets are displayed, on the server-side they're still calculated by targeting a maximum of 100,000 vbytes per fee bucket, regardless of fee rate ranges. The client-side then "squashes" the buckets to fit into the pre-defined fee-rate ranges.

For example, these fee buckets:

```
[[24.624765,103669],[19.349398,100077],[17.517643,102671],[17.111658,100631],[16.257875,103571],[15.193939,100115],[15.165104,105905],[15.162463,101163],[15.15697,107452],[15.155994,119447],[15.150459,108010],[15.122951,100093],[13.151751,100162],[11.851851,100062],[10,100212],[7,100179],[5.0349145,100532],[4.017778,100198],[3.6226416,100304],[3.0267856,100188],[3.0014925,100387],[2.8383234,100530],[2.5353982,100091],[2.0047004,105366],[1.009901,100420],[1,47695]]
```

Would be squashed into these ranges:

![image](https://user-images.githubusercontent.com/877904/53806693-50645200-3f56-11e9-8a31-e88f53ecba45.png)
